# Generated by Django 5.0 on 2023-12-17 15:32

import core.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef123456', length=10, max_length=20, prefix='pro', unique=True)),
                ('title', models.CharField(default='apple', max_length=200)),
                ('image', models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path)),
                ('description', models.TextField(default='this is a product', max_length=200)),
                ('price', models.IntegerField()),
                ('specification', models.TextField(blank=True, max_length=200, null=True)),
                ('product_status', models.CharField(choices=[('draft', 'draft'), ('disabled', 'disabled'), ('rejected', 'rejected'), ('in_review', 'in_review'), ('published', 'published')], default='in review', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('feature', models.BooleanField(default=True)),
                ('digital', models.BooleanField(default=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef12345', length=10, max_length=20, prefix='sku', unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='kumagaya', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_on_time',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='warranty_peroid',
            field=models.CharField(default='123456', max_length=200),
        ),
    ]
